name: sigsci-module-golang
on:
  push:
    branches:
      - main
  pull_request:
   

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18' ]
    name: Build ${{ matrix.go }}
    steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SIGSCI_CORE_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SIGSCI_CORE_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Conatiner
      run: |
            docker build  --tag gotest:1 .
            docker images
          
    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
          access-key-id: ${{ secrets.SIGSCI_CORE_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.SIGSCI_CORE_SECRET_ACCESS_KEY }}
          region: eu-west-1
          image: gotest:1
