name: Update release db
on: 
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SIGSCI_PROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SIGSCI_PROD_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install botocore boto3
      - name: Update metadata
        run: |
          ./scripts/update-release-metadata.py sigsci-module-golang ${{ github.ref }}
        env:
          PROD_ID: ${{ secrets.SIGSCI_PROD_CANONICAL_ID }}

