name: Update release db
on: 
  release:
    types: [released, edited]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Update metadata
        run: |
          ./scripts/update-release-metadata.py sigsci-module-golang ${{ github.ref }}
